---
- bmg: |-
    suppliers.project([:sid, :name])
  sqlite: |-
    SELECT
      `t1`.`sid`,
      `t1`.`name`
    FROM
      `suppliers` AS 't1'
- bmg: |-
    suppliers.project([:name])
  sqlite: |-
    SELECT DISTINCT
      `t1`.`name`
    FROM
      `suppliers` AS 't1'
- bmg: |-
    suppliers.allbut([:sid, :status]).project([:name])
  sqlite: |-
    SELECT DISTINCT
      `t1`.`name`
    FROM
      `suppliers` AS 't1'
